In [ ]:
import os
# from google.colab import drive
# drive.mount('/content/drive')

# %cd /content/drive/MyDrive/Files/COMP545_PROJECT

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/Files/COMP545_PROJECT

In [ ]:
import os
import json
import argparse
import pandas as pd
import numpy as np
import torch
from torch.utils.data import DataLoader
from transformers import AutoTokenizer
from tqdm import tqdm

Load Model INFO

In [ ]:
# 分别加载seen和unseen模型信息
seen_model_info_file_path = 'data/model_data/seen_models.json'
unseen_model_info_file_path = 'data/model_data/unseen_models.json'
seen_model_info = pd.read_json(seen_model_info_file_path).T
unseen_model_info = pd.read_json(unseen_model_info_file_path).T

seen_models = list(seen_model_info.index)
unseen_models = list(unseen_model_info.index)
print(f"Seen models ({len(seen_models)}): {seen_models}")
print(f"Unseen models ({len(unseen_models)}): {unseen_models}")

# 加载模型嵌入
model_embedding_file_path = 'data/embeddings/model_embeddings.json'
with open(model_embedding_file_path, 'r') as f:
    model_embeddings_raw = json.load(f)
print(f"Model embeddings: {len(model_embeddings_raw)} models, dim={len(list(model_embeddings_raw.values())[0])}")

,bbh_acc,math_acc,mmlu_pro_acc,feature_vector,co2_cost,base_model
MaziyarPanahi/calme-3.2-instruct-78b,0.729734,0.399547,0.730303,"[0.729734421107446, 0.399546827794561, 0.73030...",66.01,Qwen/Qwen2.5-72B
Qwen/Qwen2.5-0.5B-Instruct,0.330672,0.089879,0.171958,"[0.330671758375282, 0.089879154078549, 0.17195...",1.24,Qwen/Qwen2.5-0.5B
Qwen/Qwen2.5-1.5B-Instruct,0.424753,0.204683,0.27992,"[0.42475264710987604, 0.204682779456193, 0.279...",1.37,Qwen/Qwen2.5-1.5B
Qwen/Qwen2.5-14B-Instruct,0.637389,0.537764,0.490442,"[0.637389342128102, 0.5377643504531721, 0.4904...",3.55,Qwen/Qwen2.5-14B
Qwen/Qwen2.5-32B-Instruct,0.687381,0.617069,0.566656,"[0.6873806630793261, 0.6170694864048331, 0.566...",11.5,Qwen/Qwen2.5-32B
Qwen/Qwen2.5-3B-Instruct,0.465544,0.358006,0.325465,"[0.46554417635827106, 0.358006042296072, 0.325...",2.78,Qwen/Qwen2.5-3B
Qwen/Qwen2.5-72B-Instruct,0.725568,0.589124,0.562583,"[0.725568477694844, 0.589123867069486, 0.56258...",47.65,Qwen/Qwen2.5-72B
Qwen/Qwen2.5-7B-Instruct,0.536886,0.48565,0.42869,"[0.5368859572990801, 0.48564954682779404, 0.42...",3.24,Qwen/Qwen2.5-7B
deepseek-ai/DeepSeek-R1-Distill-Qwen-14B,0.591217,0.594411,0.466672,"[0.59121680263843, 0.5944108761329301, 0.46667...",3.99,Qwen/Qwen2.5-14B
deepseek-ai/DeepSeek-R1-Distill-Qwen-32B,0.417636,0.43429,0.468667,"[0.417635827113348, 0.43429003021148005, 0.468...",47.28,Qwen/Qwen2.5-32B
deepseek-ai/DeepSeek-R1-Distill-Qwen-7B,0.341087,0.432024,0.232131,"[0.34108661690678704, 0.43202416918429004, 0.2...",1.37,Qwen/Qwen2.5-7B
meta-llama/Llama-3.1-70B-Instruct,0.679917,0.379909,0.533743,"[0.6799166811317481, 0.379909365558912, 0.5337...",40.22,meta-llama/Llama-3.1-70B
meta-llama/Llama-3.1-8B-Instruct,0.507724,0.154079,0.37982,"[0.5077243534108661, 0.154078549848942, 0.3798...",2.11,meta-llama/Llama-3.1-8B
meta-llama/Llama-3.2-1B-Instruct,0.346815,0.053625,0.168218,"[0.346814789099114, 0.053625377643504, 0.16821...",0.81,meta-llama/Llama-3.2-1B
meta-llama/Llama-3.2-3B-Instruct,0.458601,0.163142,0.319481,"[0.45860093733726703, 0.163141993957703, 0.319...",1.93,meta-llama/Llama-3.2-3B
meta-llama/Llama-3.3-70B-Instruct,0.691547,0.455438,0.533162,"[0.691546606491928, 0.45543806646525603, 0.533...",76.56,meta-llama/Llama-3.1-70B

In [ ]:
# 分别构建seen和unseen模型的embedding + cost DataFrame
def build_model_embedding_cost_df(model_info_df, model_embeddings_raw):
    records = []
    for model_name in model_info_df.index:
        if model_name in model_embeddings_raw:
            records.append({
                "model_name": model_name,
                "model_embedding": model_embeddings_raw[model_name],
                "model_co2_cost": model_info_df.loc[model_name, "co2_cost"],
            })
    return pd.DataFrame(records).set_index("model_name")

seen_model_embedding_cost = build_model_embedding_cost_df(seen_model_info, model_embeddings_raw)
unseen_model_embedding_cost = build_model_embedding_cost_df(unseen_model_info, model_embeddings_raw)

print("Seen model embedding+cost:")
print(seen_model_embedding_cost)
print(f"\nUnseen model embedding+cost:")
print(unseen_model_embedding_cost)

,model_feature_vector,model_co2_cost
MaziyarPanahi/calme-3.2-instruct-78b,"[0.729734421107446, 0.399546827794561, 0.73030...",66.01
Qwen/Qwen2.5-0.5B-Instruct,"[0.330671758375282, 0.089879154078549, 0.17195...",1.24
Qwen/Qwen2.5-1.5B-Instruct,"[0.42475264710987604, 0.204682779456193, 0.279...",1.37
Qwen/Qwen2.5-14B-Instruct,"[0.637389342128102, 0.5377643504531721, 0.4904...",3.55
Qwen/Qwen2.5-32B-Instruct,"[0.6873806630793261, 0.6170694864048331, 0.566...",11.5
Qwen/Qwen2.5-3B-Instruct,"[0.46554417635827106, 0.358006042296072, 0.325...",2.78
Qwen/Qwen2.5-72B-Instruct,"[0.725568477694844, 0.589123867069486, 0.56258...",47.65
Qwen/Qwen2.5-7B-Instruct,"[0.5368859572990801, 0.48564954682779404, 0.42...",3.24
deepseek-ai/DeepSeek-R1-Distill-Qwen-14B,"[0.59121680263843, 0.5944108761329301, 0.46667...",3.99
deepseek-ai/DeepSeek-R1-Distill-Qwen-32B,"[0.417635827113348, 0.43429003021148005, 0.468...",47.28
deepseek-ai/DeepSeek-R1-Distill-Qwen-7B,"[0.34108661690678704, 0.43202416918429004, 0.2...",1.37
meta-llama/Llama-3.1-70B-Instruct,"[0.6799166811317481, 0.379909365558912, 0.5337...",40.22
meta-llama/Llama-3.1-8B-Instruct,"[0.5077243534108661, 0.154078549848942, 0.3798...",2.11
meta-llama/Llama-3.2-1B-Instruct,"[0.346814789099114, 0.053625377643504, 0.16821...",0.81
meta-llama/Llama-3.2-3B-Instruct,"[0.45860093733726703, 0.163141993957703, 0.319...",1.93
meta-llama/Llama-3.3-70B-Instruct,"[0.691546606491928, 0.45543806646525603, 0.533...",76.56

In [ ]:
# OOD查询嵌入 - 需要先通过extract_embeddings.py生成
# 如果OOD嵌入不存在，可运行:
# python extract_embeddings.py --query_input data/model_data/extracted_dataset_samples_ood.jsonl --models_info data/model_data/unseen_models.json --query_output data/embeddings/query_embeddings_ood.jsonl --model_output data/embeddings/model_embeddings_unseen.json
result_df = pd.read_json('data/embeddings/query_embeddings_ood.jsonl', lines=True)
result_df

,query_id,dataset,query,feature_vector
0,gpqa_q0,gpqa,"A large gene has dozens of exons, of which the...","[1.250377721362383e-07, 5.4702974011888734e-05..."
1,gpqa_q1,gpqa,trans-cinnamaldehyde was treated with methylma...,"[9.303163750473686e-08, 4.902486398350448e-05,..."
2,gpqa_q2,gpqa,A coating is applied to a substrate resulting ...,"[1.421572051185648e-06, 0.00036677374737300006..."
3,gpqa_q3,gpqa,"aniline is heated with sulfuric acid, forming ...","[1.282018899928516e-07, 6.299525557551533e-05,..."
4,gpqa_q4,gpqa,In a parallel universe where a magnet can have...,"[1.066538501959257e-07, 5.5897759011713795e-05..."
...,...,...,...,...
1296,musr_q751,musr,In the high-stakes world of a prestigious tale...,"[9.818778380576987e-06, 0.0006710650050080001,..."
1297,musr_q752,musr,"In the vibrant epicenter of New York City, a p...","[9.525962923362385e-06, 0.0006735900533380001,..."
1298,musr_q753,musr,"In the pulsating heart of Silicon Valley, a bu...","[5.026178314437857e-06, 0.00043655897025000006..."
1299,musr_q754,musr,"In the pulsating heart of Silicon Valley, a bu...","[1.5150058970903043e-05, 0.0008957770187400001..."
1300,musr_q755,musr,"In the dynamic realm of technology, a prestigi...","[9.505608431936707e-06, 0.000635277130641, 0.9..."

In [ ]:
# ID查询嵌入
ID_results_df = pd.read_json('data/embeddings/query_embeddings.jsonl', lines=True)
ID_results_df

,query_id,query,feature_vector,dataset
0,bbh_q0,not ( True ) and ( True ) is,"[0.999993681907653, 2.68437997874571e-06, 3.54...",bbh
1,bbh_q1,not True or False or ( False ) is,"[0.9999901056289671, 4.502644060266903e-06, 5....",bbh
2,bbh_q2,True or not False and True and False is,"[0.9999886751174921, 4.963138053426519e-06, 6....",bbh
3,bbh_q3,not True and ( False or True ) is,"[0.999993205070495, 2.932409415734582e-06, 3.8...",bbh
4,bbh_q4,not True or ( False and True ) is,"[0.999993443489074, 2.847306177500286e-06, 3.6...",bbh
...,...,...,...,...
18700,mmlu_pro_q11640,A hot mild steel rod is placed in a carbonaceo...,"[1.0312172094018019e-07, 5.0701830332400284e-0...",mmlu_pro
18701,mmlu_pro_q11641,Consider the evaporation of liquid ammonia int...,"[7.761179290355358e-07, 0.000261560897342, 0.9...",mmlu_pro
18702,mmlu_pro_q11642,The frequency range of a commercially broadcas...,"[2.3169583585058707e-07, 9.768966265255587e-05...",mmlu_pro
18703,mmlu_pro_q11643,Suppose there are 100 identical firms in a per...,"[8.748482116516243e-08, 4.565488416119478e-05,...",mmlu_pro
18704,mmlu_pro_q11644,"Let {N(t), t=[0, \infty]} be a Poisson process...","[3.757495221634599e-07, 0.00012177246389900001...",mmlu_pro

Generate perdiction reuslt for all different alpha

In [19]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np

In [ ]:
# Neural Collaborative Filtering (NeuMF) style Router with input projectors
class RouterNN(nn.Module):
    def __init__(self, query_dim, model_dim,
                 proj_dim=128,
                 latent_dim_mf=64, latent_dim_mlp=64,
                 config_layers=(512, 256, 128), dropout_rate=0.1, output_size=1):
        super(RouterNN, self).__init__()

        # --- Input projectors (two-layer) to reduce high-dim embeddings ---
        self.query_projector = nn.Sequential(
            nn.Linear(query_dim, 256),
            nn.ReLU(),
            nn.Linear(256, proj_dim),
            nn.ReLU(),
        )
        self.model_projector = nn.Sequential(
            nn.Linear(model_dim, 256),
            nn.ReLU(),
            nn.Linear(256, proj_dim),
            nn.ReLU(),
        )

        # MLP path projections (from projected dim)
        self.q_proj_mlp = nn.Linear(proj_dim, latent_dim_mlp)
        self.m_proj_mlp = nn.Linear(proj_dim, latent_dim_mlp)

        # MF path projections (from projected dim)
        self.q_proj_mf = nn.Linear(proj_dim, latent_dim_mf)
        self.m_proj_mf = nn.Linear(proj_dim, latent_dim_mf)

        # MLP layers
        self.fc_layers = nn.ModuleList()
        input_size = latent_dim_mlp * 2
        for hidden_size in config_layers:
            self.fc_layers.append(nn.Linear(input_size, hidden_size))
            input_size = hidden_size
        self.dropout = nn.Dropout(dropout_rate)

        # Output layer: MLP output + MF output
        self.output_layer = nn.Linear(config_layers[-1] + latent_dim_mf, output_size)

        self._init_weight_()

    def _init_weight_(self):
        for proj in [self.query_projector, self.model_projector]:
            for m in proj.modules():
                if isinstance(m, nn.Linear):
                    nn.init.kaiming_uniform_(m.weight, nonlinearity='relu')
                    nn.init.zeros_(m.bias)

        nn.init.normal_(self.q_proj_mlp.weight, std=0.01)
        nn.init.normal_(self.m_proj_mlp.weight, std=0.01)
        nn.init.normal_(self.q_proj_mf.weight, std=0.01)
        nn.init.normal_(self.m_proj_mf.weight, std=0.01)

        for fc in self.fc_layers:
            nn.init.xavier_uniform_(fc.weight)
            nn.init.zeros_(fc.bias)

        nn.init.kaiming_uniform_(self.output_layer.weight, nonlinearity='sigmoid')
        nn.init.zeros_(self.output_layer.bias)

    def forward(self, query, model_vec):
        # Project high-dim inputs to lower dim
        query = self.query_projector(query)
        model_vec = self.model_projector(model_vec)

        # MLP path
        q_mlp = torch.relu(self.q_proj_mlp(query))
        m_mlp = torch.relu(self.m_proj_mlp(model_vec))
        mlp_vector = torch.cat([q_mlp, m_mlp], dim=-1)

        for fc in self.fc_layers:
            mlp_vector = torch.relu(fc(mlp_vector))
            mlp_vector = self.dropout(mlp_vector)

        # MF path
        q_mf = self.q_proj_mf(query)
        m_mf = self.m_proj_mf(model_vec)
        mf_vector = torch.mul(q_mf, m_mf)

        # Concat MLP + MF
        output_vector = torch.cat([mlp_vector, mf_vector], dim=-1)

        out = self.output_layer(output_vector)
        return out

In [ ]:
def find_the_best_alpha(model_embedding_cost_df, query_embedding_df, accuracy_perdictor_model_pth, device, query_dim=768, model_dim=768):
    """
    model_embedding_cost_df: DataFrame with index=model_name, columns=[model_embedding, model_co2_cost]
    query_embedding_df: DataFrame with columns=[query_id, embedding, ...]
    """
    # model set up
    route_model = RouterNN(
        query_dim=query_dim, model_dim=model_dim,
        proj_dim=128, latent_dim_mf=64, latent_dim_mlp=64,
        config_layers=(512, 256, 128), dropout_rate=0.1, output_size=1,
    )
    route_model.load_state_dict(torch.load(accuracy_perdictor_model_pth, map_location=device))
    route_model.to(device)
    route_model.eval()

    # query df setting
    query_id_and_embedding = query_embedding_df[['query_id', 'embedding']]

    # Normalize co2 cost
    cost_min = model_embedding_cost_df['model_co2_cost'].min()
    cost_max = model_embedding_cost_df['model_co2_cost'].max()

    # Step 1: Run inference ONCE for all (query, model) pairs
    print("Running inference for all (query, model) pairs...")
    inference_cache = {}  # (query_id, model_name) -> (prob_correct, co2_cost_norm)

    for query_id, input_query_embedding in tqdm(query_id_and_embedding.itertuples(index=False), desc="Inference", total=len(query_id_and_embedding)):
        for model_name, model_embedding, co2_cost in model_embedding_cost_df.itertuples(index=True):
            input_query_tensor = torch.tensor(input_query_embedding, dtype=torch.float32).unsqueeze(0).to(device)
            model_emb_tensor = torch.tensor(model_embedding, dtype=torch.float32).unsqueeze(0).to(device)
            with torch.no_grad():
                logit = route_model(input_query_tensor, model_emb_tensor)
                prob_correct = torch.sigmoid(logit).item()
            co2_cost_norm = (co2_cost - cost_min) / (cost_max - cost_min)
            inference_cache[(query_id, model_name)] = (prob_correct, co2_cost_norm)

    # Step 2: Search alpha using cached results (no more inference)
    print("Searching best alpha...")
    query_ids = query_id_and_embedding['query_id'].tolist()
    model_names = model_embedding_cost_df.index.tolist()

    results = {}
    for alpha in tqdm(np.arange(0, 1, 0.01), desc="Alpha search"):
        query = []
        for query_id in query_ids:
            best_model_name = None
            best_score = -float('inf')
            for model_name in model_names:
                prob_correct, co2_cost_norm = inference_cache[(query_id, model_name)]
                score = (1 - alpha) * prob_correct - alpha * co2_cost_norm
                if score > best_score:
                    best_score = score
                    best_model_name = model_name
            query.append((query_id, best_model_name, best_score, alpha))
        results[alpha] = query
    return results

In [33]:
router_path = 'best_router_model.pth'
device='cuda'

In [ ]:
# ID数据评估
all_alpha_model_ID_seen = find_the_best_alpha(seen_model_embedding_cost, ID_results_df, router_path, device)
all_alpha_model_ID_unseen = find_the_best_alpha(unseen_model_embedding_cost, ID_results_df, router_path, device)

Running inference for all (query, model) pairs...

Inference: 100%|██████████| 18705/18705 [03:08<00:00, 99.20it/s]

Searching best alpha...

Alpha search: 100%|██████████| 100/100 [00:18<00:00,  5.37it/s]

In [ ]:
# OOD数据评估
all_alpha_model_OOD_seen = find_the_best_alpha(seen_model_embedding_cost, result_df, router_path, device)
all_alpha_model_OOD_unseen = find_the_best_alpha(unseen_model_embedding_cost, result_df, router_path, device)

Running inference for all (query, model) pairs...

Inference: 100%|██████████| 1301/1301 [00:13<00:00, 99.02it/s]

Searching best alpha...

Alpha search: 100%|██████████| 100/100 [00:01<00:00, 80.52it/s]

In [ ]:
# ID数据保存
all_data_ID_seen = [row for rows in all_alpha_model_ID_seen.values() for row in rows]
pd.DataFrame(all_data_ID_seen, columns=['query_id', 'best_model', 'score', 'alpha']).to_csv("all_alpha_model_ID_seen.csv", index=False)

all_data_ID_unseen = [row for rows in all_alpha_model_ID_unseen.values() for row in rows]
pd.DataFrame(all_data_ID_unseen, columns=['query_id', 'best_model', 'score', 'alpha']).to_csv("all_alpha_model_ID_unseen.csv", index=False)

print("Saved ID results.")

In [ ]:
# OOD数据保存
all_data_OOD_seen = [row for rows in all_alpha_model_OOD_seen.values() for row in rows]
pd.DataFrame(all_data_OOD_seen, columns=['query_id', 'best_model', 'score', 'alpha']).to_csv("all_alpha_model_OOD_seen.csv", index=False)

all_data_OOD_unseen = [row for rows in all_alpha_model_OOD_unseen.values() for row in rows]
pd.DataFrame(all_data_OOD_unseen, columns=['query_id', 'best_model', 'score', 'alpha']).to_csv("all_alpha_model_OOD_unseen.csv", index=False)

print("Saved OOD results.")